use crate::shop::*;
use crate::utilities;

pub fn shop_items() -> Vec<Item> {
    let items = vec![
        Item {
            texture_name: "love_potion".to_string(),
            name: "Speed Boots".to_string(),
            price: 50,
            description: "Increases movement speed by 20%".to_string(),
            level_requirement: 5,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 20,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ring of Criticals".to_string(),
            price: 100,
            description: "Increases critical chance by 5%".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 5,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Gloves of Swiftness".to_string(),
            price: 75,
            description: "Increases attack speed by 15%".to_string(),
            level_requirement: 8,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 15,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Iron Shield".to_string(),
            price: 60,
            description: "Increases defense by 30".to_string(),
            level_requirement: 3,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 30,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Range Amplifier".to_string(),
            price: 120,
            description: "Increases damage range by 20".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 200,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Power Potion".to_string(),
            price: 90,
            description: "Increases weapon damage by 2".to_string(),
            level_requirement: 1,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Bullet of Swiftness".to_string(),
            price: 110,
            description: "Increases bullet speed by 10".to_string(),
            level_requirement: 1,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 100,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Extra Weapon Slot".to_string(),
            price: 1000,
            description: "Adds an additional weapon".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ring of Fire".to_string(),
            price: 130,
            description: "Increases damage radius by 20".to_string(),
            level_requirement: 18,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 20,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Large Health Potion".to_string(),
            price: 30,
            description: "Restores 100 health".to_string(),
            level_requirement: 2,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 100,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Mystic Ring".to_string(),
            price: 500,
            description: "Increases critical damage by 10%".to_string(),
            level_requirement: 25,
            attributes: Attributes {
                attribute_type: "critical_damage".to_string(),
                quantity: 10,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Glorious Ring".to_string(),
            price: 500,
            description: "Increases critical damage by 8%".to_string(),
            level_requirement: 25,
            attributes: Attributes {
                attribute_type: "critical_damage".to_string(),
                quantity: 8,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Warrior's Helm".to_string(),
            price: 80,
            description: "Increases defense by 10".to_string(),
            level_requirement: 1,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 10,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Potion of Swiftness".to_string(),
            price: 200,
            description: "Increases movement speed by 15% for 60 seconds".to_string(),
            level_requirement: 1,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 15,
                duration: 60,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Gloves of Quickness".to_string(),
            price: 5000,
            description: "Increases attack speed by 20%".to_string(),
            level_requirement: 50,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 20,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Sniper Scope".to_string(),
            price: 150,
            description: "Increases damage range by 50".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 50,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Damage Booster".to_string(),
            price: 120,
            description: "Increases weapon damage by 10".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 10,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Bullet Surge".to_string(),
            price: 135,
            description: "Increases bullet speed by 150".to_string(),
            level_requirement: 14,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Multi-Weapon Mastery".to_string(),
            price: 7500,
            description: "Adds 2 additional weapons".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 2,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Blast Radius Enhancer".to_string(),
            price: 10000,
            description: "Increases damage radius by 100".to_string(),
            level_requirement: 60,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 100,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Giant Health Potion".to_string(),
            price: 45,
            description: "Restores 200 health".to_string(),
            level_requirement: 5,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 200,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Shadow Boots".to_string(),
            price: 90,
            description: "Increases movement speed by 25%".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ring of Power".to_string(),
            price: 140,
            description: "Increases critical chance by 10%".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 10,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Quick Blades".to_string(),
            price: 85,
            description: "Increases attack speed by 18%".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 18,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Guardian Shield".to_string(),
            price: 70,
            description: "Increases defense by 40".to_string(),
            level_requirement: 8,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 40,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Sniper Amplifier".to_string(),
            price: 160,
            description: "Increases damage range by 350".to_string(),
            level_requirement: 18,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 350,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Potion of Power".to_string(),
            price: 110,
            description: "Increases weapon damage by 30".to_string(),
            level_requirement: 13,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 30,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Bullet Quickener".to_string(),
            price: 125,
            description: "Increases bullet speed by 120".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 120,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Double Weapon Slot".to_string(),
            price: 180,
            description: "Adds an additional weapon".to_string(),
            level_requirement: 25,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Radius Enhancer".to_string(),
            price: 170,
            description: "Increases damage radius by 70".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 70,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Super Health Potion".to_string(),
            price: 55,
            description: "Restores 250 health".to_string(),
            level_requirement: 7,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 250,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Boots of Swiftness".to_string(),
            price: 65,
            description: "Increases movement speed by 12%".to_string(),
            level_requirement: 5,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 12,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Necklace of Criticals".to_string(),
            price: 135,
            description: "Increases critical chance by 8%".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 8,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Blades of Speed".to_string(),
            price: 95,
            description: "Increases attack speed by 22%".to_string(),
            level_requirement: 14,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 22,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Heavy Shield".to_string(),
            price: 75,
            description: "Increases defense by 45".to_string(),
            level_requirement: 6,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 45,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Range Extender".to_string(),
            price: 145,
            description: "Increases damage range by 250".to_string(),
            level_requirement: 17,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 250,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Weapon Enhancer".to_string(),
            price: 130,
            description: "Increases weapon damage by 40".to_string(),
            level_requirement: 16,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 40,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Bullet Speed-Up".to_string(),
            price: 115,
            description: "Increases bullet speed by 90".to_string(),
            level_requirement: 11,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 90,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Triple Weapon Slot".to_string(),
            price: 10000,
            description: "Adds 3 additional weapons".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 3,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Radius Booster".to_string(),
            price: 160,
            description: "Increases damage radius by 90".to_string(),
            level_requirement: 23,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 90,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Mega Health Potion".to_string(),
            price: 65,
            description: "Restores 300 health".to_string(),
            level_requirement: 8,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 300,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Winged Boots".to_string(),
            price: 85,
            description: "Increases movement speed by 18%".to_string(),
            level_requirement: 9,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 18,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Crown of Criticals".to_string(),
            price: 160,
            description: "Increases critical chance by 12%".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 12,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Quick Sword".to_string(),
            price: 95,
            description: "Increases attack speed by 20%".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 20,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Iron Defender".to_string(),
            price: 85,
            description: "Increases defense by 35".to_string(),
            level_requirement: 9,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 35,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Long Range Scope".to_string(),
            price: 160,
            description: "Increases damage range by 300".to_string(),
            level_requirement: 22,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 300,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Strength Potion".to_string(),
            price: 100,
            description: "Increases weapon damage by 35".to_string(),
            level_requirement: 14,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 35,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Accelerated Bullets".to_string(),
            price: 125,
            description: "Increases bullet speed by 130".to_string(),
            level_requirement: 13,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 130,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Extra Weapon Slot".to_string(),
            price: 190,
            description: "Adds an additional weapon slot".to_string(),
            level_requirement: 28,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Huge Radius Enhancer".to_string(),
            price: 190,
            description: "Increases damage radius by 120".to_string(),
            level_requirement: 25,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 120,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Giant Health Potion".to_string(),
            price: 70,
            description: "Restores 350 health".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 350,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Agility Boots".to_string(),
            price: 80,
            description: "Increases movement speed by 15%".to_string(),
            level_requirement: 7,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 15,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Critical Amulet".to_string(),
            price: 155,
            description: "Increases critical chance by 15%".to_string(),
            level_requirement: 18,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 15,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Blades of Haste".to_string(),
            price: 115,
            description: "Increases attack speed by 25%".to_string(),
            level_requirement: 16,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Fortress Shield".to_string(),
            price: 90,
            description: "Increases defense by 50".to_string(),
            level_requirement: 11,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 50,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Sniper Ring".to_string(),
            price: 175,
            description: "Increases damage range by 400".to_string(),
            level_requirement: 22,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 400,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Strength Elixir".to_string(),
            price: 140,
            description: "Increases weapon damage by 45".to_string(),
            level_requirement: 17,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 45,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Rapid Bullets".to_string(),
            price: 135,
            description: "Increases bullet speed by 150".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Fourth Weapon Slot".to_string(),
            price: 230,
            description: "Adds 1 additional weapon slot".to_string(),
            level_requirement: 35,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Giant Radius Booster".to_string(),
            price: 200,
            description: "Increases damage radius by 150".to_string(),
            level_requirement: 30,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ultimate Health Potion".to_string(),
            price: 85,
            description: "Restores 400 health".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 400,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Speedy Boots".to_string(),
            price: 95,
            description: "Increases movement speed by 20%".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 20,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Critical Wristband".to_string(),
            price: 165,
            description: "Increases critical chance by 18%".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 18,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Blades of Agility".to_string(),
            price: 120,
            description: "Increases attack speed by 26%".to_string(),
            level_requirement: 18,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 26,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Elite Shield".to_string(),
            price: 95,
            description: "Increases defense by 55".to_string(),
            level_requirement: 13,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 55,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Damage Scope".to_string(),
            price: 180,
            description: "Increases damage range by 500".to_string(),
            level_requirement: 24,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 500,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Power Boost".to_string(),
            price: 150,
            description: "Increases weapon damage by 50".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 50,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ultra Bullets".to_string(),
            price: 140,
            description: "Increases bullet speed by 170".to_string(),
            level_requirement: 18,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 170,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Fifth Weapon Slot".to_string(),
            price: 270,
            description: "Adds 1 additional weapon slot".to_string(),
            level_requirement: 40,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Colossal Radius Booster".to_string(),
            price: 220,
            description: "Increases damage radius by 150".to_string(),
            level_requirement: 35,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Super Health Potion".to_string(),
            price: 100,
            description: "Restores 500 health".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 500,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Boots".to_string(),
            price: 105,
            description: "Increases movement speed by 25%".to_string(),
            level_requirement: 15,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Critical Band".to_string(),
            price: 175,
            description: "Increases critical chance by 20%".to_string(),
            level_requirement: 22,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 20,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Super Blades".to_string(),
            price: 130,
            description: "Increases attack speed by 30%".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 30,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Diamond Shield".to_string(),
            price: 110,
            description: "Increases defense by 60".to_string(),
            level_requirement: 16,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 60,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ultimate Range Scope".to_string(),
            price: 200,
            description: "Increases damage range by 600".to_string(),
            level_requirement: 28,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 600,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ultimate Damage Boost".to_string(),
            price: 175,
            description: "Increases weapon damage by 60".to_string(),
            level_requirement: 22,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 60,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Hyper Bullets".to_string(),
            price: 155,
            description: "Increases bullet speed by 200".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 200,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Sixth Weapon Slot".to_string(),
            price: 300,
            description: "Adds 1 additional weapon slot".to_string(),
            level_requirement: 45,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ultimate Radius Booster".to_string(),
            price: 250,
            description: "Increases damage radius by 150".to_string(),
            level_requirement: 40,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Mega Health Potion".to_string(),
            price: 120,
            description: "Restores 600 health".to_string(),
            level_requirement: 18,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 600,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Ultimate Boots".to_string(),
            price: 130,
            description: "Increases movement speed by 30%".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 30,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Critical Ring".to_string(),
            price: 190,
            description: "Increases critical chance by 25%".to_string(),
            level_requirement: 25,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Blades".to_string(),
            price: 145,
            description: "Increases attack speed by 35%".to_string(),
            level_requirement: 22,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 35,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Shield".to_string(),
            price: 125,
            description: "Increases defense by 70".to_string(),
            level_requirement: 20,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 70,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Range Scope".to_string(),
            price: 225,
            description: "Increases damage range by 800".to_string(),
            level_requirement: 30,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 800,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Damage Boost".to_string(),
            price: 200,
            description: "Increases weapon damage by 75".to_string(),
            level_requirement: 28,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 75,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Bullets".to_string(),
            price: 175,
            description: "Increases bullet speed by 250".to_string(),
            level_requirement: 25,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 250,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Weapon Slot".to_string(),
            price: 340,
            description: "Adds 1 additional weapon slot".to_string(),
            level_requirement: 50,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Radius Booster".to_string(),
            price: 300,
            description: "Increases damage radius by 200".to_string(),
            level_requirement: 45,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 200,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Health Potion".to_string(),
            price: 150,
            description: "Restores 750 health".to_string(),
            level_requirement: 30,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 750,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Legendary Boots".to_string(),
            price: 150,
            description: "Increases movement speed by 35%".to_string(),
            level_requirement: 30,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 35,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Speed Potion".to_string(),
            price: 60,
            description: "Increases movement speed by 10%".to_string(),
            level_requirement: 5,
            attributes: Attributes {
                attribute_type: "movement_speed".to_string(),
                quantity: 10,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Critical Rune".to_string(),
            price: 130,
            description: "Increases critical chance by 12%".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "critical_chance".to_string(),
                quantity: 12,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Quick Blades".to_string(),
            price: 90,
            description: "Increases attack speed by 18%".to_string(),
            level_requirement: 8,
            attributes: Attributes {
                attribute_type: "attack_speed".to_string(),
                quantity: 18,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Defense Shield".to_string(),
            price: 75,
            description: "Increases defense by 25".to_string(),
            level_requirement: 6,
            attributes: Attributes {
                attribute_type: "defense".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Short Range Scope".to_string(),
            price: 120,
            description: "Increases damage range by 150".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "damage_range".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Damage Potion".to_string(),
            price: 110,
            description: "Increases weapon damage by 25".to_string(),
            level_requirement: 9,
            attributes: Attributes {
                attribute_type: "weapon_damage".to_string(),
                quantity: 25,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Fast Bullets".to_string(),
            price: 105,
            description: "Increases bullet speed by 90".to_string(),
            level_requirement: 8,
            attributes: Attributes {
                attribute_type: "bullet_speed".to_string(),
                quantity: 90,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Extra Slot".to_string(),
            price: 145,
            description: "Adds an additional weapon slot".to_string(),
            level_requirement: 12,
            attributes: Attributes {
                attribute_type: "weapon_count".to_string(),
                quantity: 1,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Small Radius Booster".to_string(),
            price: 70,
            description: "Increases damage radius by 50".to_string(),
            level_requirement: 5,
            attributes: Attributes {
                attribute_type: "damage_radius".to_string(),
                quantity: 50,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Major Health Potion".to_string(),
            price: 55,
            description: "Restores 150 health".to_string(),
            level_requirement: 4,
            attributes: Attributes {
                attribute_type: "player_health".to_string(),
                quantity: 150,
                duration: 0,
            },
        },
        Item {
            texture_name: "love_potion".to_string(),
            name: "Nuclear ammo".to_string(),
            price: 5000,
            description: "Increases AoE targets by 1".to_string(),
            level_requirement: 10,
            attributes: Attributes {
                attribute_type: "aoe_targets".to_string(),
                quantity: 1,
                duration: 0,
            },
        }
    ];
    items
}

pub fn get_four_items_from_list(mut max_level: u32) -> Vec<Item> {
    // Filter items within the specified level range
    if max_level < 1 {
        max_level = 1
    }
    let mut items = shop_items();
    items.retain(|item| item.level_requirement <= max_level);
    utilities::get_random_elements(&mut items, 4)
}